######################################################################
# Automatically generated by qmake (2.01a) Sun Nov 22 15:35:26 2009
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += MainWindow.h
FORMS += MainWindow.ui
SOURCES += main.cpp MainWindow.cpp
