######################################################################
# Automatically generated by qmake (2.01a) Sun Jul 25 18:49:39 2010
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

QT += opengl

# Input
HEADERS += AppWindow.h GLThread.h GLWidget.h
SOURCES += AppWindow.cpp GLThread.cpp GLWidget.cpp main.cpp
