######################################################################
# Automatically generated by qmake (2.01a) Wed Nov 11 11:55:56 2009
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .
	

QT += core \
	network \
	xml
	
# Input
HEADERS += HttpServer.h TestServer.h SimpleTemplate.h
SOURCES += HttpServer.cpp main.cpp TestServer.cpp SimpleTemplate.cpp
