######################################################################
# Automatically generated by qmake (2.01a) Wed Sep 16 17:40:09 2009
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

QT += sql

# Input
HEADERS += SongRecord.h SongRecordListModel.h
SOURCES += main.cpp SongRecord.cpp SongRecordListModel.cpp
