######################################################################
# Automatically generated by qmake (1.07a) Sat Nov 7 21:39:09 2009
######################################################################

TEMPLATE = app
INCLUDEPATH += .

QT = core network

# Input
HEADERS += BibleGatewayConnector.h
SOURCES += main.cpp BibleGatewayConnector.cpp
