#include "BibleModel.h"
bool BibleVerseRef::bookNameMap_initalized = false;
QHash<QString,QString> BibleVerseRef::bookNameMap;
QStringList BibleVerseRef::bookNameList;
void BibleVerseRef::initNameMap()
{
	if(bookNameMap_initalized)
	return;
	bookNameMap["gen"] = "Genesis";
	bookNameList << "Gen";
	bookNameMap["ge"] = "Genesis";
	bookNameList << "Ge";
	bookNameMap["gn"] = "Genesis";
	bookNameList << "Gn";
	bookNameMap["genesis"] = "Genesis";
	bookNameList << "Genesis";
	bookNameMap["exo"] = "Exodus";
	bookNameList << "Exo";
	bookNameMap["ex"] = "Exodus";
	bookNameList << "Ex";
	bookNameMap["exod"] = "Exodus";
	bookNameList << "Exod";
	bookNameMap["exodus"] = "Exodus";
	bookNameList << "Exodus";
	bookNameMap["lev"] = "Leviticus";
	bookNameList << "Lev";
	bookNameMap["le"] = "Leviticus";
	bookNameList << "Le";
	bookNameMap["lv"] = "Leviticus";
	bookNameList << "Lv";
	bookNameMap["leviticus"] = "Leviticus";
	bookNameList << "Leviticus";
	bookNameMap["num"] = "Numbers";
	bookNameList << "Num";
	bookNameMap["nu"] = "Numbers";
	bookNameList << "Nu";
	bookNameMap["nm"] = "Numbers";
	bookNameList << "Nm";
	bookNameMap["nb"] = "Numbers";
	bookNameList << "Nb";
	bookNameMap["numbers"] = "Numbers";
	bookNameList << "Numbers";
	bookNameMap["deut"] = "Deuteronomy";
	bookNameList << "Deut";
	bookNameMap["dt"] = "Deuteronomy";
	bookNameList << "Dt";
	bookNameMap["deuteronomy"] = "Deuteronomy";
	bookNameList << "Deuteronomy";
	bookNameMap["josh"] = "Joshua";
	bookNameList << "Josh";
	bookNameMap["jos"] = "Joshua";
	bookNameList << "Jos";
	bookNameMap["jsh"] = "Joshua";
	bookNameList << "Jsh";
	bookNameMap["joshua"] = "Joshua";
	bookNameList << "Joshua";
	bookNameMap["judg"] = "Judges";
	bookNameList << "Judg";
	bookNameMap["jdg"] = "Judges";
	bookNameList << "Jdg";
	bookNameMap["jg"] = "Judges";
	bookNameList << "Jg";
	bookNameMap["jdgs"] = "Judges";
	bookNameList << "Jdgs";
	bookNameMap["judges"] = "Judges";
	bookNameList << "Judges";
	bookNameMap["rth"] = "Ruth";
	bookNameList << "Rth";
	bookNameMap["ru"] = "Ruth";
	bookNameList << "Ru";
	bookNameMap["ruth"] = "Ruth";
	bookNameList << "Ruth";
	bookNameMap["1 sam"] = "1 Samuel";
	bookNameList << "1 Sam";
	bookNameMap["1 sa"] = "1 Samuel";
	bookNameList << "1 Sa";
	bookNameMap["1samuel"] = "1 Samuel";
	bookNameList << "1Samuel";
	bookNameMap["1s"] = "1 Samuel";
	bookNameList << "1S";
	bookNameMap["i sa"] = "1 Samuel";
	bookNameList << "I Sa";
	bookNameMap["1 sm"] = "1 Samuel";
	bookNameList << "1 Sm";
	bookNameMap["1sa"] = "1 Samuel";
	bookNameList << "1Sa";
	bookNameMap["i sam"] = "1 Samuel";
	bookNameList << "I Sam";
	bookNameMap["1sam"] = "1 Samuel";
	bookNameList << "1Sam";
	bookNameMap["i samuel"] = "1 Samuel";
	bookNameList << "I Samuel";
	bookNameMap["1st samuel"] = "1 Samuel";
	bookNameList << "1st Samuel";
	bookNameMap["first samuel"] = "1 Samuel";
	bookNameList << "First Samuel";
	bookNameMap["1 samuel"] = "1 Samuel";
	bookNameList << "1 Samuel";
	bookNameMap["2 sam"] = "2 Samuel";
	bookNameList << "2 Sam";
	bookNameMap["2 sa"] = "2 Samuel";
	bookNameList << "2 Sa";
	bookNameMap["2s"] = "2 Samuel";
	bookNameList << "2S";
	bookNameMap["ii sa"] = "2 Samuel";
	bookNameList << "II Sa";
	bookNameMap["2 sm"] = "2 Samuel";
	bookNameList << "2 Sm";
	bookNameMap["2sa"] = "2 Samuel";
	bookNameList << "2Sa";
	bookNameMap["ii sam"] = "2 Samuel";
	bookNameList << "II Sam";
	bookNameMap["2sam"] = "2 Samuel";
	bookNameList << "2Sam";
	bookNameMap["ii samuel"] = "2 Samuel";
	bookNameList << "II Samuel";
	bookNameMap["2samuel"] = "2 Samuel";
	bookNameList << "2Samuel";
	bookNameMap["2nd samuel"] = "2 Samuel";
	bookNameList << "2nd Samuel";
	bookNameMap["second samuel"] = "2 Samuel";
	bookNameList << "Second Samuel";
	bookNameMap["2 samuel"] = "2 Samuel";
	bookNameList << "2 Samuel";
	bookNameMap["1 kgs"] = "1 Kings";
	bookNameList << "1 Kgs";
	bookNameMap["1 ki"] = "1 Kings";
	bookNameList << "1 Ki";
	bookNameMap["1k"] = "1 Kings";
	bookNameList << "1K";
	bookNameMap["i kgs"] = "1 Kings";
	bookNameList << "I Kgs";
	bookNameMap["1kgs"] = "1 Kings";
	bookNameList << "1Kgs";
	bookNameMap["i ki"] = "1 Kings";
	bookNameList << "I Ki";
	bookNameMap["1ki"] = "1 Kings";
	bookNameList << "1Ki";
	bookNameMap["i kings"] = "1 Kings";
	bookNameList << "I Kings";
	bookNameMap["1kings"] = "1 Kings";
	bookNameList << "1Kings";
	bookNameMap["1st kgs"] = "1 Kings";
	bookNameList << "1st Kgs";
	bookNameMap["1st kings"] = "1 Kings";
	bookNameList << "1st Kings";
	bookNameMap["first kings"] = "1 Kings";
	bookNameList << "First Kings";
	bookNameMap["first kgs"] = "1 Kings";
	bookNameList << "First Kgs";
	bookNameMap["1kin"] = "1 Kings";
	bookNameList << "1Kin";
	bookNameMap["1 kings"] = "1 Kings";
	bookNameList << "1 Kings";
	bookNameMap["2 kgs"] = "2 Kings";
	bookNameList << "2 Kgs";
	bookNameMap["2 ki"] = "2 Kings";
	bookNameList << "2 Ki";
	bookNameMap["2k"] = "2 Kings";
	bookNameList << "2K";
	bookNameMap["ii kgs"] = "2 Kings";
	bookNameList << "II Kgs";
	bookNameMap["2kgs"] = "2 Kings";
	bookNameList << "2Kgs";
	bookNameMap["ii ki"] = "2 Kings";
	bookNameList << "II Ki";
	bookNameMap["2ki"] = "2 Kings";
	bookNameList << "2Ki";
	bookNameMap["ii kings"] = "2 Kings";
	bookNameList << "II Kings";
	bookNameMap["2kings"] = "2 Kings";
	bookNameList << "2Kings";
	bookNameMap["2nd kgs"] = "2 Kings";
	bookNameList << "2nd Kgs";
	bookNameMap["2nd kings"] = "2 Kings";
	bookNameList << "2nd Kings";
	bookNameMap["second kings"] = "2 Kings";
	bookNameList << "Second Kings";
	bookNameMap["second kgs"] = "2 Kings";
	bookNameList << "Second Kgs";
	bookNameMap["2kin"] = "2 Kings";
	bookNameList << "2Kin";
	bookNameMap["2 kings"] = "2 Kings";
	bookNameList << "2 Kings";
	bookNameMap["1 chron"] = "1 Chronicles";
	bookNameList << "1 Chron";
	bookNameMap["1 ch"] = "1 Chronicles";
	bookNameList << "1 Ch";
	bookNameMap["i ch"] = "1 Chronicles";
	bookNameList << "I Ch";
	bookNameMap["1ch"] = "1 Chronicles";
	bookNameList << "1Ch";
	bookNameMap["1 chr"] = "1 Chronicles";
	bookNameList << "1 Chr";
	bookNameMap["i chr"] = "1 Chronicles";
	bookNameList << "I Chr";
	bookNameMap["1chr"] = "1 Chronicles";
	bookNameList << "1Chr";
	bookNameMap["i chron"] = "1 Chronicles";
	bookNameList << "I Chron";
	bookNameMap["1chron"] = "1 Chronicles";
	bookNameList << "1Chron";
	bookNameMap["i chronicles"] = "1 Chronicles";
	bookNameList << "I Chronicles";
	bookNameMap["1chronicles"] = "1 Chronicles";
	bookNameList << "1Chronicles";
	bookNameMap["1st chronicles"] = "1 Chronicles";
	bookNameList << "1st Chronicles";
	bookNameMap["first chronicles"] = "1 Chronicles";
	bookNameList << "First Chronicles";
	bookNameMap["1 chronicles"] = "1 Chronicles";
	bookNameList << "1 Chronicles";
	bookNameMap["2 chron"] = "2 Chronicles";
	bookNameList << "2 Chron";
	bookNameMap["2 ch"] = "2 Chronicles";
	bookNameList << "2 Ch";
	bookNameMap["ii ch"] = "2 Chronicles";
	bookNameList << "II Ch";
	bookNameMap["2ch"] = "2 Chronicles";
	bookNameList << "2Ch";
	bookNameMap["ii chr"] = "2 Chronicles";
	bookNameList << "II Chr";
	bookNameMap["2chr"] = "2 Chronicles";
	bookNameList << "2Chr";
	bookNameMap["ii chron"] = "2 Chronicles";
	bookNameList << "II Chron";
	bookNameMap["2chron"] = "2 Chronicles";
	bookNameList << "2Chron";
	bookNameMap["ii chronicles"] = "2 Chronicles";
	bookNameList << "II Chronicles";
	bookNameMap["2chronicles"] = "2 Chronicles";
	bookNameList << "2Chronicles";
	bookNameMap["2nd chronicles"] = "2 Chronicles";
	bookNameList << "2nd Chronicles";
	bookNameMap["second chronicles"] = "2 Chronicles";
	bookNameList << "Second Chronicles";
	bookNameMap["2 chronicles"] = "2 Chronicles";
	bookNameList << "2 Chronicles";
	bookNameMap["ezra"] = "Ezra";
	bookNameList << "Ezra";
	bookNameMap["ezr"] = "Ezra";
	bookNameList << "Ezr";
	bookNameMap["ezra"] = "Ezra";
	bookNameList << "Ezra";
	bookNameMap["neh"] = "Nehemiah";
	bookNameList << "Neh";
	bookNameMap["ne"] = "Nehemiah";
	bookNameList << "Ne";
	bookNameMap["nehemiah"] = "Nehemiah";
	bookNameList << "Nehemiah";
	bookNameMap["esth"] = "Esther";
	bookNameList << "Esth";
	bookNameMap["es"] = "Esther";
	bookNameList << "Es";
	bookNameMap["esther"] = "Esther";
	bookNameList << "Esther";
	bookNameMap["job"] = "Job";
	bookNameList << "Job";
	bookNameMap["job"] = "Job";
	bookNameList << "Job";
	bookNameMap["jb"] = "Job";
	bookNameList << "Jb";
	bookNameMap["job"] = "Job";
	bookNameList << "Job";
	bookNameMap["pslm"] = "Psalm";
	bookNameList << "Pslm";
	bookNameMap["ps"] = "Psalm";
	bookNameList << "Ps";
	bookNameMap["psalms"] = "Psalm";
	bookNameList << "Psalms";
	bookNameMap["psa"] = "Psalm";
	bookNameList << "Psa";
	bookNameMap["psm"] = "Psalm";
	bookNameList << "Psm";
	bookNameMap["pss"] = "Psalm";
	bookNameList << "Pss";
	bookNameMap["psalm"] = "Psalm";
	bookNameList << "Psalm";
	bookNameMap["prov"] = "Proverbs";
	bookNameList << "Prov";
	bookNameMap["pr"] = "Proverbs";
	bookNameList << "Pr";
	bookNameMap["prv"] = "Proverbs";
	bookNameList << "Prv";
	bookNameMap["proverbs"] = "Proverbs";
	bookNameList << "Proverbs";
	bookNameMap["eccles"] = "Ecclesiastes";
	bookNameList << "Eccles";
	bookNameMap["ec"] = "Ecclesiastes";
	bookNameList << "Ec";
	bookNameMap["qoh"] = "Ecclesiastes";
	bookNameList << "Qoh";
	bookNameMap["qoheleth"] = "Ecclesiastes";
	bookNameList << "Qoheleth";
	bookNameMap["ecclesiastes"] = "Ecclesiastes";
	bookNameList << "Ecclesiastes";
	bookNameMap["song"] = "Song of Solomon";
	bookNameList << "Song";
	bookNameMap["so"] = "Song of Solomon";
	bookNameList << "So";
	bookNameMap["canticle of canticles"] = "Song of Solomon";
	bookNameList << "Canticle of Canticles";
	bookNameMap["canticles"] = "Song of Solomon";
	bookNameList << "Canticles";
	bookNameMap["song of songs"] = "Song of Solomon";
	bookNameList << "Song of Songs";
	bookNameMap["sos"] = "Song of Solomon";
	bookNameList << "SOS";
	bookNameMap["song of solomon"] = "Song of Solomon";
	bookNameList << "Song of Solomon";
	bookNameMap["isa"] = "Isaiah";
	bookNameList << "Isa";
	bookNameMap["is"] = "Isaiah";
	bookNameList << "Is";
	bookNameMap["isaiah"] = "Isaiah";
	bookNameList << "Isaiah";
	bookNameMap["jer"] = "Jeremiah";
	bookNameList << "Jer";
	bookNameMap["je"] = "Jeremiah";
	bookNameList << "Je";
	bookNameMap["jr"] = "Jeremiah";
	bookNameList << "Jr";
	bookNameMap["jeremiah"] = "Jeremiah";
	bookNameList << "Jeremiah";
	bookNameMap["lam"] = "Lamentations";
	bookNameList << "Lam";
	bookNameMap["la"] = "Lamentations";
	bookNameList << "La";
	bookNameMap["lamentations"] = "Lamentations";
	bookNameList << "Lamentations";
	bookNameMap["ezek"] = "Ezekiel";
	bookNameList << "Ezek";
	bookNameMap["eze"] = "Ezekiel";
	bookNameList << "Eze";
	bookNameMap["ezk"] = "Ezekiel";
	bookNameList << "Ezk";
	bookNameMap["ezekiel"] = "Ezekiel";
	bookNameList << "Ezekiel";
	bookNameMap["dan"] = "Daniel";
	bookNameList << "Dan";
	bookNameMap["da"] = "Daniel";
	bookNameList << "Da";
	bookNameMap["dn"] = "Daniel";
	bookNameList << "Dn";
	bookNameMap["daniel"] = "Daniel";
	bookNameList << "Daniel";
	bookNameMap["hos"] = "Hosea";
	bookNameList << "Hos";
	bookNameMap["ho"] = "Hosea";
	bookNameList << "Ho";
	bookNameMap["hosea"] = "Hosea";
	bookNameList << "Hosea";
	bookNameMap["joel"] = "Joel";
	bookNameList << "Joel";
	bookNameMap["joe"] = "Joel";
	bookNameList << "Joe";
	bookNameMap["jl"] = "Joel";
	bookNameList << "Jl";
	bookNameMap["joel"] = "Joel";
	bookNameList << "Joel";
	bookNameMap["amos"] = "Amos";
	bookNameList << "Amos";
	bookNameMap["am"] = "Amos";
	bookNameList << "Am";
	bookNameMap["amos"] = "Amos";
	bookNameList << "Amos";
	bookNameMap["obad"] = "Obadiah";
	bookNameList << "Obad";
	bookNameMap["ob"] = "Obadiah";
	bookNameList << "Ob";
	bookNameMap["obadiah"] = "Obadiah";
	bookNameList << "Obadiah";
	bookNameMap["jnh"] = "Jonah";
	bookNameList << "Jnh";
	bookNameMap["jon"] = "Jonah";
	bookNameList << "Jon";
	bookNameMap["jonah"] = "Jonah";
	bookNameList << "Jonah";
	bookNameMap["micah"] = "Micah";
	bookNameList << "Micah";
	bookNameMap["mic"] = "Micah";
	bookNameList << "Mic";
	bookNameMap["micah"] = "Micah";
	bookNameList << "Micah";
	bookNameMap["nah"] = "Nahum";
	bookNameList << "Nah";
	bookNameMap["na"] = "Nahum";
	bookNameList << "Na";
	bookNameMap["nahum"] = "Nahum";
	bookNameList << "Nahum";
	bookNameMap["hab"] = "Habakkuk";
	bookNameList << "Hab";
	bookNameMap["hab"] = "Habakkuk";
	bookNameList << "Hab";
	bookNameMap["habakkuk"] = "Habakkuk";
	bookNameList << "Habakkuk";
	bookNameMap["zeph"] = "Zephaniah";
	bookNameList << "Zeph";
	bookNameMap["zep"] = "Zephaniah";
	bookNameList << "Zep";
	bookNameMap["zp"] = "Zephaniah";
	bookNameList << "Zp";
	bookNameMap["zephaniah"] = "Zephaniah";
	bookNameList << "Zephaniah";
	bookNameMap["haggai"] = "Haggai";
	bookNameList << "Haggai";
	bookNameMap["hag"] = "Haggai";
	bookNameList << "Hag";
	bookNameMap["hg"] = "Haggai";
	bookNameList << "Hg";
	bookNameMap["haggai"] = "Haggai";
	bookNameList << "Haggai";
	bookNameMap["zech"] = "Zechariah";
	bookNameList << "Zech";
	bookNameMap["zec"] = "Zechariah";
	bookNameList << "Zec";
	bookNameMap["zc"] = "Zechariah";
	bookNameList << "Zc";
	bookNameMap["zechariah"] = "Zechariah";
	bookNameList << "Zechariah";
	bookNameMap["mal"] = "Malachi";
	bookNameList << "Mal";
	bookNameMap["mal"] = "Malachi";
	bookNameList << "Mal";
	bookNameMap["ml"] = "Malachi";
	bookNameList << "Ml";
	bookNameMap["malachi"] = "Malachi";
	bookNameList << "Malachi";
	bookNameMap["tobit"] = "Tobit";
	bookNameList << "Tobit";
	bookNameMap["tob"] = "Tobit";
	bookNameList << "Tob";
	bookNameMap["tb"] = "Tobit";
	bookNameList << "Tb";
	bookNameMap["tobit"] = "Tobit";
	bookNameList << "Tobit";
	bookNameMap["jdth"] = "Judith";
	bookNameList << "Jdth";
	bookNameMap["jdt"] = "Judith";
	bookNameList << "Jdt";
	bookNameMap["jth"] = "Judith";
	bookNameList << "Jth";
	bookNameMap["judith"] = "Judith";
	bookNameList << "Judith";
	bookNameMap["add esth"] = "Additions to Esther";
	bookNameList << "Add Esth";
	bookNameMap["add es"] = "Additions to Esther";
	bookNameList << "Add Es";
	bookNameMap["rest of esther"] = "Additions to Esther";
	bookNameList << "Rest of Esther";
	bookNameMap["the rest of esther"] = "Additions to Esther";
	bookNameList << "The Rest of Esther";
	bookNameMap["aes"] = "Additions to Esther";
	bookNameList << "AEs";
	bookNameMap["addesth"] = "Additions to Esther";
	bookNameList << "AddEsth";
	bookNameMap["additions to esther"] = "Additions to Esther";
	bookNameList << "Additions to Esther";
	bookNameMap["wisd of sol"] = "Wisdom of Solomon";
	bookNameList << "Wisd of Sol";
	bookNameMap["wis"] = "Wisdom of Solomon";
	bookNameList << "Wis";
	bookNameMap["ws"] = "Wisdom of Solomon";
	bookNameList << "Ws";
	bookNameMap["wisdom"] = "Wisdom of Solomon";
	bookNameList << "Wisdom";
	bookNameMap["wisdom of solomon"] = "Wisdom of Solomon";
	bookNameList << "Wisdom of Solomon";
	bookNameMap["sirach"] = "Sirach";
	bookNameList << "Sirach";
	bookNameMap["sir"] = "Sirach";
	bookNameList << "Sir";
	bookNameMap["ecclesiasticus"] = "Sirach";
	bookNameList << "Ecclesiasticus";
	bookNameMap["ecclus"] = "Sirach";
	bookNameList << "Ecclus";
	bookNameMap["sirach"] = "Sirach";
	bookNameList << "Sirach";
	bookNameMap["baruch"] = "Baruch";
	bookNameList << "Baruch";
	bookNameMap["bar"] = "Baruch";
	bookNameList << "Bar";
	bookNameMap["baruch"] = "Baruch";
	bookNameList << "Baruch";
	bookNameMap["let jer"] = "Letter of Jeremiah";
	bookNameList << "Let Jer";
	bookNameMap["let jer"] = "Letter of Jeremiah";
	bookNameList << "Let Jer";
	bookNameMap["lje"] = "Letter of Jeremiah";
	bookNameList << "LJe";
	bookNameMap["ltr jer"] = "Letter of Jeremiah";
	bookNameList << "Ltr Jer";
	bookNameMap["letter of jeremiah"] = "Letter of Jeremiah";
	bookNameList << "Letter of Jeremiah";
	bookNameMap["song of three"] = "Song of Three Youths";
	bookNameList << "Song of Three";
	bookNameMap["song thr"] = "Song of Three Youths";
	bookNameList << "Song Thr";
	bookNameMap["the song of three youths"] = "Song of Three Youths";
	bookNameList << "The Song of Three Youths";
	bookNameMap["pr az"] = "Song of Three Youths";
	bookNameList << "Pr Az";
	bookNameMap["prayer of azariah"] = "Song of Three Youths";
	bookNameList << "Prayer of Azariah";
	bookNameMap["azariah"] = "Song of Three Youths";
	bookNameList << "Azariah";
	bookNameMap["the song of the three holy children"] = "Song of Three Youths";
	bookNameList << "The Song of the Three Holy Children";
	bookNameMap["the song of three jews"] = "Song of Three Youths";
	bookNameList << "The Song of Three Jews";
	bookNameMap["song of the three holy children"] = "Song of Three Youths";
	bookNameList << "Song of the Three Holy Children";
	bookNameMap["song of thr"] = "Song of Three Youths";
	bookNameList << "Song of Thr";
	bookNameMap["song of three children"] = "Song of Three Youths";
	bookNameList << "Song of Three Children";
	bookNameMap["song of three jews"] = "Song of Three Youths";
	bookNameList << "Song of Three Jews";
	bookNameMap["song of three youths"] = "Song of Three Youths";
	bookNameList << "Song of Three Youths";
	bookNameMap["susanna"] = "Susanna";
	bookNameList << "Susanna";
	bookNameMap["sus"] = "Susanna";
	bookNameList << "Sus";
	bookNameMap["susanna"] = "Susanna";
	bookNameList << "Susanna";
	bookNameMap["bel"] = "Bel and the Dragon";
	bookNameList << "Bel";
	bookNameMap["bel"] = "Bel and the Dragon";
	bookNameList << "Bel";
	bookNameMap["bel and the dragon"] = "Bel and the Dragon";
	bookNameList << "Bel and the Dragon";
	bookNameMap["1 macc"] = "1 Maccabees";
	bookNameList << "1 Macc";
	bookNameMap["1 mac"] = "1 Maccabees";
	bookNameList << "1 Mac";
	bookNameMap["1m"] = "1 Maccabees";
	bookNameList << "1M";
	bookNameMap["i ma"] = "1 Maccabees";
	bookNameList << "I Ma";
	bookNameMap["1ma"] = "1 Maccabees";
	bookNameList << "1Ma";
	bookNameMap["i mac"] = "1 Maccabees";
	bookNameList << "I Mac";
	bookNameMap["1mac"] = "1 Maccabees";
	bookNameList << "1Mac";
	bookNameMap["i macc"] = "1 Maccabees";
	bookNameList << "I Macc";
	bookNameMap["1macc"] = "1 Maccabees";
	bookNameList << "1Macc";
	bookNameMap["i maccabees"] = "1 Maccabees";
	bookNameList << "I Maccabees";
	bookNameMap["1maccabees"] = "1 Maccabees";
	bookNameList << "1Maccabees";
	bookNameMap["1st maccabees"] = "1 Maccabees";
	bookNameList << "1st Maccabees";
	bookNameMap["first maccabees"] = "1 Maccabees";
	bookNameList << "First Maccabees";
	bookNameMap["1 maccabees"] = "1 Maccabees";
	bookNameList << "1 Maccabees";
	bookNameMap["2 macc"] = "2 Maccabees";
	bookNameList << "2 Macc";
	bookNameMap["2 mac"] = "2 Maccabees";
	bookNameList << "2 Mac";
	bookNameMap["2m"] = "2 Maccabees";
	bookNameList << "2M";
	bookNameMap["ii ma"] = "2 Maccabees";
	bookNameList << "II Ma";
	bookNameMap["2ma"] = "2 Maccabees";
	bookNameList << "2Ma";
	bookNameMap["ii mac"] = "2 Maccabees";
	bookNameList << "II Mac";
	bookNameMap["2mac"] = "2 Maccabees";
	bookNameList << "2Mac";
	bookNameMap["ii macc"] = "2 Maccabees";
	bookNameList << "II Macc";
	bookNameMap["2macc"] = "2 Maccabees";
	bookNameList << "2Macc";
	bookNameMap["ii maccabees"] = "2 Maccabees";
	bookNameList << "II Maccabees";
	bookNameMap["2maccabees"] = "2 Maccabees";
	bookNameList << "2Maccabees";
	bookNameMap["2nd maccabees"] = "2 Maccabees";
	bookNameList << "2nd Maccabees";
	bookNameMap["second maccabees"] = "2 Maccabees";
	bookNameList << "Second Maccabees";
	bookNameMap["2 maccabees"] = "2 Maccabees";
	bookNameList << "2 Maccabees";
	bookNameMap["1 esdr"] = "1 Esdras";
	bookNameList << "1 Esdr";
	bookNameMap["1 esd"] = "1 Esdras";
	bookNameList << "1 Esd";
	bookNameMap["i es"] = "1 Esdras";
	bookNameList << "I Es";
	bookNameMap["1es"] = "1 Esdras";
	bookNameList << "1Es";
	bookNameMap["i esd"] = "1 Esdras";
	bookNameList << "I Esd";
	bookNameMap["1esd"] = "1 Esdras";
	bookNameList << "1Esd";
	bookNameMap["i esdr"] = "1 Esdras";
	bookNameList << "I Esdr";
	bookNameMap["1esdr"] = "1 Esdras";
	bookNameList << "1Esdr";
	bookNameMap["i esdras"] = "1 Esdras";
	bookNameList << "I Esdras";
	bookNameMap["1esdras"] = "1 Esdras";
	bookNameList << "1Esdras";
	bookNameMap["1st esdras"] = "1 Esdras";
	bookNameList << "1st Esdras";
	bookNameMap["first esdras"] = "1 Esdras";
	bookNameList << "First Esdras";
	bookNameMap["1 esdras"] = "1 Esdras";
	bookNameList << "1 Esdras";
	bookNameMap["pr of man"] = "Prayer of Manasseh";
	bookNameList << "Pr of Man";
	bookNameMap["pr man"] = "Prayer of Manasseh";
	bookNameList << "Pr Man";
	bookNameMap["pma"] = "Prayer of Manasseh";
	bookNameList << "PMa";
	bookNameMap["prayer of manasses"] = "Prayer of Manasseh";
	bookNameList << "Prayer of Manasses";
	bookNameMap["prayer of manasseh"] = "Prayer of Manasseh";
	bookNameList << "Prayer of Manasseh";
	bookNameMap["add psalm"] = "Additional Psalm";
	bookNameList << "Add Psalm";
	bookNameMap["add ps"] = "Additional Psalm";
	bookNameList << "Add Ps";
	bookNameMap["additional psalm"] = "Additional Psalm";
	bookNameList << "Additional Psalm";
	bookNameMap["3 macc"] = "3 Maccabees";
	bookNameList << "3 Macc";
	bookNameMap["3 mac"] = "3 Maccabees";
	bookNameList << "3 Mac";
	bookNameMap["iii ma"] = "3 Maccabees";
	bookNameList << "III Ma";
	bookNameMap["3ma"] = "3 Maccabees";
	bookNameList << "3Ma";
	bookNameMap["iii mac"] = "3 Maccabees";
	bookNameList << "III Mac";
	bookNameMap["3mac"] = "3 Maccabees";
	bookNameList << "3Mac";
	bookNameMap["iii macc"] = "3 Maccabees";
	bookNameList << "III Macc";
	bookNameMap["3macc"] = "3 Maccabees";
	bookNameList << "3Macc";
	bookNameMap["iii maccabees"] = "3 Maccabees";
	bookNameList << "III Maccabees";
	bookNameMap["3rd maccabees"] = "3 Maccabees";
	bookNameList << "3rd Maccabees";
	bookNameMap["third maccabees"] = "3 Maccabees";
	bookNameList << "Third Maccabees";
	bookNameMap["3 maccabees"] = "3 Maccabees";
	bookNameList << "3 Maccabees";
	bookNameMap["2 esdr"] = "2 Esdras";
	bookNameList << "2 Esdr";
	bookNameMap["2 esd"] = "2 Esdras";
	bookNameList << "2 Esd";
	bookNameMap["ii es"] = "2 Esdras";
	bookNameList << "II Es";
	bookNameMap["2es"] = "2 Esdras";
	bookNameList << "2Es";
	bookNameMap["ii esd"] = "2 Esdras";
	bookNameList << "II Esd";
	bookNameMap["2esd"] = "2 Esdras";
	bookNameList << "2Esd";
	bookNameMap["ii esdr"] = "2 Esdras";
	bookNameList << "II Esdr";
	bookNameMap["2esdr"] = "2 Esdras";
	bookNameList << "2Esdr";
	bookNameMap["ii esdras"] = "2 Esdras";
	bookNameList << "II Esdras";
	bookNameMap["2esdras"] = "2 Esdras";
	bookNameList << "2Esdras";
	bookNameMap["2nd esdras"] = "2 Esdras";
	bookNameList << "2nd Esdras";
	bookNameMap["second esdras"] = "2 Esdras";
	bookNameList << "Second Esdras";
	bookNameMap["2 esdras"] = "2 Esdras";
	bookNameList << "2 Esdras";
	bookNameMap["4 macc"] = "4 Maccabees";
	bookNameList << "4 Macc";
	bookNameMap["4 mac"] = "4 Maccabees";
	bookNameList << "4 Mac";
	bookNameMap["iv ma"] = "4 Maccabees";
	bookNameList << "IV Ma";
	bookNameMap["4ma"] = "4 Maccabees";
	bookNameList << "4Ma";
	bookNameMap["iv mac"] = "4 Maccabees";
	bookNameList << "IV Mac";
	bookNameMap["4mac"] = "4 Maccabees";
	bookNameList << "4Mac";
	bookNameMap["iv macc"] = "4 Maccabees";
	bookNameList << "IV Macc";
	bookNameMap["4macc"] = "4 Maccabees";
	bookNameList << "4Macc";
	bookNameMap["iv maccabees"] = "4 Maccabees";
	bookNameList << "IV Maccabees";
	bookNameMap["iiii maccabees"] = "4 Maccabees";
	bookNameList << "IIII Maccabees";
	bookNameMap["4maccabees"] = "4 Maccabees";
	bookNameList << "4Maccabees";
	bookNameMap["4th maccabees"] = "4 Maccabees";
	bookNameList << "4th Maccabees";
	bookNameMap["fourth maccabees"] = "4 Maccabees";
	bookNameList << "Fourth Maccabees";
	bookNameMap["4 maccabees"] = "4 Maccabees";
	bookNameList << "4 Maccabees";
	bookNameMap["ode"] = "Ode";
	bookNameList << "Ode";
	bookNameMap["ode"] = "Ode";
	bookNameList << "Ode";
	bookNameMap["ode"] = "Ode";
	bookNameList << "Ode";
	bookNameMap["ps solomon"] = "Psalms of Solomon";
	bookNameList << "Ps Solomon";
	bookNameMap["ps sol"] = "Psalms of Solomon";
	bookNameList << "Ps Sol";
	bookNameMap["psalms solomon"] = "Psalms of Solomon";
	bookNameList << "Psalms Solomon";
	bookNameMap["pssol"] = "Psalms of Solomon";
	bookNameList << "PsSol";
	bookNameMap["psalms of solomon"] = "Psalms of Solomon";
	bookNameList << "Psalms of Solomon";
	bookNameMap["laodiceans"] = "Epistle to the Laodiceans";
	bookNameList << "Laodiceans";
	bookNameMap["laod"] = "Epistle to the Laodiceans";
	bookNameList << "Laod";
	bookNameMap["ep laod"] = "Epistle to the Laodiceans";
	bookNameList << "Ep Laod";
	bookNameMap["epist laodiceans"] = "Epistle to the Laodiceans";
	bookNameList << "Epist Laodiceans";
	bookNameMap["epistle laodiceans"] = "Epistle to the Laodiceans";
	bookNameList << "Epistle Laodiceans";
	bookNameMap["epistle to laodiceans"] = "Epistle to the Laodiceans";
	bookNameList << "Epistle to Laodiceans";
	bookNameMap["epistle to the laodiceans"] = "Epistle to the Laodiceans";
	bookNameList << "Epistle to the Laodiceans";
	bookNameMap["matt"] = "Matthew";
	bookNameList << "Matt";
	bookNameMap["mt"] = "Matthew";
	bookNameList << "Mt";
	bookNameMap["matthew"] = "Matthew";
	bookNameList << "Matthew";
	bookNameMap["mrk"] = "Mark";
	bookNameList << "Mrk";
	bookNameMap["mk"] = "Mark";
	bookNameList << "Mk";
	bookNameMap["mr"] = "Mark";
	bookNameList << "Mr";
	bookNameMap["mark"] = "Mark";
	bookNameList << "Mark";
	bookNameMap["luk"] = "Luke";
	bookNameList << "Luk";
	bookNameMap["lk"] = "Luke";
	bookNameList << "Lk";
	bookNameMap["luke"] = "Luke";
	bookNameList << "Luke";
	bookNameMap["john"] = "John";
	bookNameList << "John";
	bookNameMap["jn"] = "John";
	bookNameList << "Jn";
	bookNameMap["jhn"] = "John";
	bookNameList << "Jhn";
	bookNameMap["john"] = "John";
	bookNameList << "John";
	bookNameMap["acts"] = "Acts";
	bookNameList << "Acts";
	bookNameMap["ac"] = "Acts";
	bookNameList << "Ac";
	bookNameMap["acts"] = "Acts";
	bookNameList << "Acts";
	bookNameMap["rom"] = "Romans";
	bookNameList << "Rom";
	bookNameMap["ro"] = "Romans";
	bookNameList << "Ro";
	bookNameMap["rm"] = "Romans";
	bookNameList << "Rm";
	bookNameMap["romans"] = "Romans";
	bookNameList << "Romans";
	bookNameMap["1 cor"] = "1 Corinthians";
	bookNameList << "1 Cor";
	bookNameMap["1 co"] = "1 Corinthians";
	bookNameList << "1 Co";
	bookNameMap["i co"] = "1 Corinthians";
	bookNameList << "I Co";
	bookNameMap["1co"] = "1 Corinthians";
	bookNameList << "1Co";
	bookNameMap["i cor"] = "1 Corinthians";
	bookNameList << "I Cor";
	bookNameMap["1cor"] = "1 Corinthians";
	bookNameList << "1Cor";
	bookNameMap["i corinthians"] = "1 Corinthians";
	bookNameList << "I Corinthians";
	bookNameMap["1corinthians"] = "1 Corinthians";
	bookNameList << "1Corinthians";
	bookNameMap["1st corinthians"] = "1 Corinthians";
	bookNameList << "1st Corinthians";
	bookNameMap["first corinthians"] = "1 Corinthians";
	bookNameList << "First Corinthians";
	bookNameMap["1 corinthians"] = "1 Corinthians";
	bookNameList << "1 Corinthians";
	bookNameMap["2 cor"] = "2 Corinthians";
	bookNameList << "2 Cor";
	bookNameMap["2 co"] = "2 Corinthians";
	bookNameList << "2 Co";
	bookNameMap["ii co"] = "2 Corinthians";
	bookNameList << "II Co";
	bookNameMap["2co"] = "2 Corinthians";
	bookNameList << "2Co";
	bookNameMap["ii cor"] = "2 Corinthians";
	bookNameList << "II Cor";
	bookNameMap["2cor"] = "2 Corinthians";
	bookNameList << "2Cor";
	bookNameMap["ii corinthians"] = "2 Corinthians";
	bookNameList << "II Corinthians";
	bookNameMap["2corinthians"] = "2 Corinthians";
	bookNameList << "2Corinthians";
	bookNameMap["2nd corinthians"] = "2 Corinthians";
	bookNameList << "2nd Corinthians";
	bookNameMap["second corinthians"] = "2 Corinthians";
	bookNameList << "Second Corinthians";
	bookNameMap["2 corinthians"] = "2 Corinthians";
	bookNameList << "2 Corinthians";
	bookNameMap["gal"] = "Galatians";
	bookNameList << "Gal";
	bookNameMap["ga"] = "Galatians";
	bookNameList << "Ga";
	bookNameMap["galatians"] = "Galatians";
	bookNameList << "Galatians";
	bookNameMap["ephes"] = "Ephesians";
	bookNameList << "Ephes";
	bookNameMap["eph"] = "Ephesians";
	bookNameList << "Eph";
	bookNameMap["ephesians"] = "Ephesians";
	bookNameList << "Ephesians";
	bookNameMap["phil"] = "Philippians";
	bookNameList << "Phil";
	bookNameMap["php"] = "Philippians";
	bookNameList << "Php";
	bookNameMap["philippians"] = "Philippians";
	bookNameList << "Philippians";
	bookNameMap["col"] = "Colossians";
	bookNameList << "Col";
	bookNameMap["col"] = "Colossians";
	bookNameList << "Col";
	bookNameMap["colossians"] = "Colossians";
	bookNameList << "Colossians";
	bookNameMap["1 thess"] = "1 Thessalonians";
	bookNameList << "1 Thess";
	bookNameMap["1 th"] = "1 Thessalonians";
	bookNameList << "1 Th";
	bookNameMap["i th"] = "1 Thessalonians";
	bookNameList << "I Th";
	bookNameMap["1th"] = "1 Thessalonians";
	bookNameList << "1Th";
	bookNameMap["i thes"] = "1 Thessalonians";
	bookNameList << "I Thes";
	bookNameMap["1thes"] = "1 Thessalonians";
	bookNameList << "1Thes";
	bookNameMap["i thess"] = "1 Thessalonians";
	bookNameList << "I Thess";
	bookNameMap["1thess"] = "1 Thessalonians";
	bookNameList << "1Thess";
	bookNameMap["i thessalonians"] = "1 Thessalonians";
	bookNameList << "I Thessalonians";
	bookNameMap["1thessalonians"] = "1 Thessalonians";
	bookNameList << "1Thessalonians";
	bookNameMap["1st thessalonians"] = "1 Thessalonians";
	bookNameList << "1st Thessalonians";
	bookNameMap["first thessalonians"] = "1 Thessalonians";
	bookNameList << "First Thessalonians";
	bookNameMap["1 thessalonians"] = "1 Thessalonians";
	bookNameList << "1 Thessalonians";
	bookNameMap["2 thess"] = "2 Thessalonians";
	bookNameList << "2 Thess";
	bookNameMap["2 th"] = "2 Thessalonians";
	bookNameList << "2 Th";
	bookNameMap["ii th"] = "2 Thessalonians";
	bookNameList << "II Th";
	bookNameMap["2th"] = "2 Thessalonians";
	bookNameList << "2Th";
	bookNameMap["ii thes"] = "2 Thessalonians";
	bookNameList << "II Thes";
	bookNameMap["2thes"] = "2 Thessalonians";
	bookNameList << "2Thes";
	bookNameMap["ii thess"] = "2 Thessalonians";
	bookNameList << "II Thess";
	bookNameMap["2thess"] = "2 Thessalonians";
	bookNameList << "2Thess";
	bookNameMap["ii thessalonians"] = "2 Thessalonians";
	bookNameList << "II Thessalonians";
	bookNameMap["2thessalonians"] = "2 Thessalonians";
	bookNameList << "2Thessalonians";
	bookNameMap["2nd thessalonians"] = "2 Thessalonians";
	bookNameList << "2nd Thessalonians";
	bookNameMap["second thessalonians"] = "2 Thessalonians";
	bookNameList << "Second Thessalonians";
	bookNameMap["2 thessalonians"] = "2 Thessalonians";
	bookNameList << "2 Thessalonians";
	bookNameMap["1 tim"] = "1 Timothy";
	bookNameList << "1 Tim";
	bookNameMap["1 ti"] = "1 Timothy";
	bookNameList << "1 Ti";
	bookNameMap["i ti"] = "1 Timothy";
	bookNameList << "I Ti";
	bookNameMap["1ti"] = "1 Timothy";
	bookNameList << "1Ti";
	bookNameMap["i tim"] = "1 Timothy";
	bookNameList << "I Tim";
	bookNameMap["1tim"] = "1 Timothy";
	bookNameList << "1Tim";
	bookNameMap["i timothy"] = "1 Timothy";
	bookNameList << "I Timothy";
	bookNameMap["1timothy"] = "1 Timothy";
	bookNameList << "1Timothy";
	bookNameMap["1st timothy"] = "1 Timothy";
	bookNameList << "1st Timothy";
	bookNameMap["first timothy"] = "1 Timothy";
	bookNameList << "First Timothy";
	bookNameMap["1 timothy"] = "1 Timothy";
	bookNameList << "1 Timothy";
	bookNameMap["2 tim"] = "2 Timothy";
	bookNameList << "2 Tim";
	bookNameMap["2 ti"] = "2 Timothy";
	bookNameList << "2 Ti";
	bookNameMap["ii ti"] = "2 Timothy";
	bookNameList << "II Ti";
	bookNameMap["2ti"] = "2 Timothy";
	bookNameList << "2Ti";
	bookNameMap["ii tim"] = "2 Timothy";
	bookNameList << "II Tim";
	bookNameMap["2tim"] = "2 Timothy";
	bookNameList << "2Tim";
	bookNameMap["ii timothy"] = "2 Timothy";
	bookNameList << "II Timothy";
	bookNameMap["2timothy"] = "2 Timothy";
	bookNameList << "2Timothy";
	bookNameMap["2nd timothy"] = "2 Timothy";
	bookNameList << "2nd Timothy";
	bookNameMap["second timothy"] = "2 Timothy";
	bookNameList << "Second Timothy";
	bookNameMap["2 timothy"] = "2 Timothy";
	bookNameList << "2 Timothy";
	bookNameMap["titus"] = "Titus";
	bookNameList << "Titus";
	bookNameMap["tit"] = "Titus";
	bookNameList << "Tit";
	bookNameMap["titus"] = "Titus";
	bookNameList << "Titus";
	bookNameMap["philem"] = "Philemon";
	bookNameList << "Philem";
	bookNameMap["phm"] = "Philemon";
	bookNameList << "Phm";
	bookNameMap["philemon"] = "Philemon";
	bookNameList << "Philemon";
	bookNameMap["hebrews"] = "Hebrews";
	bookNameList << "Hebrews";
	bookNameMap["heb"] = "Hebrews";
	bookNameList << "Heb";
	bookNameMap["hebrews"] = "Hebrews";
	bookNameList << "Hebrews";
	bookNameMap["james"] = "James";
	bookNameList << "James";
	bookNameMap["jas"] = "James";
	bookNameList << "Jas";
	bookNameMap["jm"] = "James";
	bookNameList << "Jm";
	bookNameMap["james"] = "James";
	bookNameList << "James";
	bookNameMap["1 pet"] = "1 Peter";
	bookNameList << "1 Pet";
	bookNameMap["1 pe"] = "1 Peter";
	bookNameList << "1 Pe";
	bookNameMap["i pe"] = "1 Peter";
	bookNameList << "I Pe";
	bookNameMap["1pe"] = "1 Peter";
	bookNameList << "1Pe";
	bookNameMap["i pet"] = "1 Peter";
	bookNameList << "I Pet";
	bookNameMap["1pet"] = "1 Peter";
	bookNameList << "1Pet";
	bookNameMap["i pt"] = "1 Peter";
	bookNameList << "I Pt";
	bookNameMap["1 pt"] = "1 Peter";
	bookNameList << "1 Pt";
	bookNameMap["1pt"] = "1 Peter";
	bookNameList << "1Pt";
	bookNameMap["i peter"] = "1 Peter";
	bookNameList << "I Peter";
	bookNameMap["1peter"] = "1 Peter";
	bookNameList << "1Peter";
	bookNameMap["1st peter"] = "1 Peter";
	bookNameList << "1st Peter";
	bookNameMap["first peter"] = "1 Peter";
	bookNameList << "First Peter";
	bookNameMap["1 peter"] = "1 Peter";
	bookNameList << "1 Peter";
	bookNameMap["2 pet"] = "2 Peter";
	bookNameList << "2 Pet";
	bookNameMap["2 pe"] = "2 Peter";
	bookNameList << "2 Pe";
	bookNameMap["ii pe"] = "2 Peter";
	bookNameList << "II Pe";
	bookNameMap["2pe"] = "2 Peter";
	bookNameList << "2Pe";
	bookNameMap["ii pet"] = "2 Peter";
	bookNameList << "II Pet";
	bookNameMap["2pet"] = "2 Peter";
	bookNameList << "2Pet";
	bookNameMap["ii pt"] = "2 Peter";
	bookNameList << "II Pt";
	bookNameMap["2 pt"] = "2 Peter";
	bookNameList << "2 Pt";
	bookNameMap["2pt"] = "2 Peter";
	bookNameList << "2Pt";
	bookNameMap["ii peter"] = "2 Peter";
	bookNameList << "II Peter";
	bookNameMap["2peter"] = "2 Peter";
	bookNameList << "2Peter";
	bookNameMap["2nd peter"] = "2 Peter";
	bookNameList << "2nd Peter";
	bookNameMap["second peter"] = "2 Peter";
	bookNameList << "Second Peter";
	bookNameMap["2 peter"] = "2 Peter";
	bookNameList << "2 Peter";
	bookNameMap["1 john"] = "1 John";
	bookNameList << "1 John";
	bookNameMap["1 jn"] = "1 John";
	bookNameList << "1 Jn";
	bookNameMap["i jn"] = "1 John";
	bookNameList << "I Jn";
	bookNameMap["1jn"] = "1 John";
	bookNameList << "1Jn";
	bookNameMap["i jo"] = "1 John";
	bookNameList << "I Jo";
	bookNameMap["1jo"] = "1 John";
	bookNameList << "1Jo";
	bookNameMap["i joh"] = "1 John";
	bookNameList << "I Joh";
	bookNameMap["1joh"] = "1 John";
	bookNameList << "1Joh";
	bookNameMap["i jhn"] = "1 John";
	bookNameList << "I Jhn";
	bookNameMap["1 jhn"] = "1 John";
	bookNameList << "1 Jhn";
	bookNameMap["1jhn"] = "1 John";
	bookNameList << "1Jhn";
	bookNameMap["i john"] = "1 John";
	bookNameList << "I John";
	bookNameMap["1john"] = "1 John";
	bookNameList << "1John";
	bookNameMap["1st john"] = "1 John";
	bookNameList << "1st John";
	bookNameMap["first john"] = "1 John";
	bookNameList << "First John";
	bookNameMap["1 john"] = "1 John";
	bookNameList << "1 John";
	bookNameMap["2 john"] = "2 John";
	bookNameList << "2 John";
	bookNameMap["2 jn"] = "2 John";
	bookNameList << "2 Jn";
	bookNameMap["ii jn"] = "2 John";
	bookNameList << "II Jn";
	bookNameMap["2jn"] = "2 John";
	bookNameList << "2Jn";
	bookNameMap["ii jo"] = "2 John";
	bookNameList << "II Jo";
	bookNameMap["2jo"] = "2 John";
	bookNameList << "2Jo";
	bookNameMap["ii joh"] = "2 John";
	bookNameList << "II Joh";
	bookNameMap["2joh"] = "2 John";
	bookNameList << "2Joh";
	bookNameMap["ii jhn"] = "2 John";
	bookNameList << "II Jhn";
	bookNameMap["2 jhn"] = "2 John";
	bookNameList << "2 Jhn";
	bookNameMap["2jhn"] = "2 John";
	bookNameList << "2Jhn";
	bookNameMap["ii john"] = "2 John";
	bookNameList << "II John";
	bookNameMap["2john"] = "2 John";
	bookNameList << "2John";
	bookNameMap["2nd john"] = "2 John";
	bookNameList << "2nd John";
	bookNameMap["second john"] = "2 John";
	bookNameList << "Second John";
	bookNameMap["2 john"] = "2 John";
	bookNameList << "2 John";
	bookNameMap["3 john"] = "3 John";
	bookNameList << "3 John";
	bookNameMap["3 jn"] = "3 John";
	bookNameList << "3 Jn";
	bookNameMap["iii jn"] = "3 John";
	bookNameList << "III Jn";
	bookNameMap["3jn"] = "3 John";
	bookNameList << "3Jn";
	bookNameMap["iii jo"] = "3 John";
	bookNameList << "III Jo";
	bookNameMap["3jo"] = "3 John";
	bookNameList << "3Jo";
	bookNameMap["iii joh"] = "3 John";
	bookNameList << "III Joh";
	bookNameMap["3joh"] = "3 John";
	bookNameList << "3Joh";
	bookNameMap["iii jhn"] = "3 John";
	bookNameList << "III Jhn";
	bookNameMap["3 jhn"] = "3 John";
	bookNameList << "3 Jhn";
	bookNameMap["3jhn"] = "3 John";
	bookNameList << "3Jhn";
	bookNameMap["iii john"] = "3 John";
	bookNameList << "III John";
	bookNameMap["3john"] = "3 John";
	bookNameList << "3John";
	bookNameMap["3rd john"] = "3 John";
	bookNameList << "3rd John";
	bookNameMap["third john"] = "3 John";
	bookNameList << "Third John";
	bookNameMap["3 john"] = "3 John";
	bookNameList << "3 John";
	bookNameMap["jude"] = "Jude";
	bookNameList << "Jude";
	bookNameMap["jud"] = "Jude";
	bookNameList << "Jud";
	bookNameMap["jude"] = "Jude";
	bookNameList << "Jude";
	bookNameMap["rev"] = "Revelation";
	bookNameList << "Rev";
	bookNameMap["re"] = "Revelation";
	bookNameList << "Re";
	bookNameMap["the revelation"] = "Revelation";
	bookNameList << "The Revelation";
	bookNameMap["revelation"] = "Revelation";
	bookNameList << "Revelation";
	bookNameMap_initalized = true;
}
QRegExp BibleVerseRef::referenceExtractRegExp("((?:gen|ge|gn|genesis|exo|ex|exod|exodus|lev|le|lv|leviticus|num|nu|nm|nb|numbers|deut|dt|deuteronomy|josh|jos|jsh|joshua|judg|jdg|jg|jdgs|judges|rth|ru|ruth|1 sam|1 sa|1samuel|1s|i sa|1 sm|1sa|i sam|1sam|i samuel|1st samuel|first samuel|1 samuel|2 sam|2 sa|2s|ii sa|2 sm|2sa|ii sam|2sam|ii samuel|2samuel|2nd samuel|second samuel|2 samuel|1 kgs|1 ki|1k|i kgs|1kgs|i ki|1ki|i kings|1kings|1st kgs|1st kings|first kings|first kgs|1kin|1 kings|2 kgs|2 ki|2k|ii kgs|2kgs|ii ki|2ki|ii kings|2kings|2nd kgs|2nd kings|second kings|second kgs|2kin|2 kings|1 chron|1 ch|i ch|1ch|1 chr|i chr|1chr|i chron|1chron|i chronicles|1chronicles|1st chronicles|first chronicles|1 chronicles|2 chron|2 ch|ii ch|2ch|ii chr|2chr|ii chron|2chron|ii chronicles|2chronicles|2nd chronicles|second chronicles|2 chronicles|ezra|ezr|ezra|neh|ne|nehemiah|esth|es|esther|job|job|jb|job|pslm|ps|psalms|psa|psm|pss|psalm|prov|pr|prv|proverbs|eccles|ec|qoh|qoheleth|ecclesiastes|song|so|canticle of canticles|canticles|song of songs|sos|song of solomon|isa|is|isaiah|jer|je|jr|jeremiah|lam|la|lamentations|ezek|eze|ezk|ezekiel|dan|da|dn|daniel|hos|ho|hosea|joel|joe|jl|joel|amos|am|amos|obad|ob|obadiah|jnh|jon|jonah|micah|mic|micah|nah|na|nahum|hab|hab|habakkuk|zeph|zep|zp|zephaniah|haggai|hag|hg|haggai|zech|zec|zc|zechariah|mal|mal|ml|malachi|tobit|tob|tb|tobit|jdth|jdt|jth|judith|add esth|add es|rest of esther|the rest of esther|aes|addesth|additions to esther|wisd of sol|wis|ws|wisdom|wisdom of solomon|sirach|sir|ecclesiasticus|ecclus|sirach|baruch|bar|baruch|let jer|let jer|lje|ltr jer|letter of jeremiah|song of three|song thr|the song of three youths|pr az|prayer of azariah|azariah|the song of the three holy children|the song of three jews|song of the three holy children|song of thr|song of three children|song of three jews|song of three youths|susanna|sus|susanna|bel|bel|bel and the dragon|1 macc|1 mac|1m|i ma|1ma|i mac|1mac|i macc|1macc|i maccabees|1maccabees|1st maccabees|first maccabees|1 maccabees|2 macc|2 mac|2m|ii ma|2ma|ii mac|2mac|ii macc|2macc|ii maccabees|2maccabees|2nd maccabees|second maccabees|2 maccabees|1 esdr|1 esd|i es|1es|i esd|1esd|i esdr|1esdr|i esdras|1esdras|1st esdras|first esdras|1 esdras|pr of man|pr man|pma|prayer of manasses|prayer of manasseh|add psalm|add ps|additional psalm|3 macc|3 mac|iii ma|3ma|iii mac|3mac|iii macc|3macc|iii maccabees|3rd maccabees|third maccabees|3 maccabees|2 esdr|2 esd|ii es|2es|ii esd|2esd|ii esdr|2esdr|ii esdras|2esdras|2nd esdras|second esdras|2 esdras|4 macc|4 mac|iv ma|4ma|iv mac|4mac|iv macc|4macc|iv maccabees|iiii maccabees|4maccabees|4th maccabees|fourth maccabees|4 maccabees|ode|ode|ode|ps solomon|ps sol|psalms solomon|pssol|psalms of solomon|laodiceans|laod|ep laod|epist laodiceans|epistle laodiceans|epistle to laodiceans|epistle to the laodiceans|matt|mt|matthew|mrk|mk|mr|mark|luk|lk|luke|john|jn|jhn|john|acts|ac|acts|rom|ro|rm|romans|1 cor|1 co|i co|1co|i cor|1cor|i corinthians|1corinthians|1st corinthians|first corinthians|1 corinthians|2 cor|2 co|ii co|2co|ii cor|2cor|ii corinthians|2corinthians|2nd corinthians|second corinthians|2 corinthians|gal|ga|galatians|ephes|eph|ephesians|phil|php|philippians|col|col|colossians|1 thess|1 th|i th|1th|i thes|1thes|i thess|1thess|i thessalonians|1thessalonians|1st thessalonians|first thessalonians|1 thessalonians|2 thess|2 th|ii th|2th|ii thes|2thes|ii thess|2thess|ii thessalonians|2thessalonians|2nd thessalonians|second thessalonians|2 thessalonians|1 tim|1 ti|i ti|1ti|i tim|1tim|i timothy|1timothy|1st timothy|first timothy|1 timothy|2 tim|2 ti|ii ti|2ti|ii tim|2tim|ii timothy|2timothy|2nd timothy|second timothy|2 timothy|titus|tit|titus|philem|phm|philemon|hebrews|heb|hebrews|james|jas|jm|james|1 pet|1 pe|i pe|1pe|i pet|1pet|i pt|1 pt|1pt|i peter|1peter|1st peter|first peter|1 peter|2 pet|2 pe|ii pe|2pe|ii pet|2pet|ii pt|2 pt|2pt|ii peter|2peter|2nd peter|second peter|2 peter|1 john|1 jn|i jn|1jn|i jo|1jo|i joh|1joh|i jhn|1 jhn|1jhn|i john|1john|1st john|first john|1 john|2 john|2 jn|ii jn|2jn|ii jo|2jo|ii joh|2joh|ii jhn|2 jhn|2jhn|ii john|2john|2nd john|second john|2 john|3 john|3 jn|iii jn|3jn|iii jo|3jo|iii joh|3joh|iii jhn|3 jhn|3jhn|iii john|3john|3rd john|third john|3 john|jude|jud|jude|rev|re|the revelation|revelation)\\s+(?:[0-9]+)(?:[:\\.][0-9]+)?(?:\\s*-\\s*[0-9]+)?)",Qt::CaseInsensitive);
