# Makefile.in generated automatically by automake 1.5 from Makefile.am.

# Copyright 1994, 1995, 1996, 1997, 1998, 1999, 2000, 2001
# Free Software Foundation, Inc.
# This Makefile.in is free software; the Free Software Foundation
# gives unlimited permission to copy and/or distribute it,
# with or without modifications, as long as this notice is preserved.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY, to the extent permitted by law; without
# even the implied warranty of MERCHANTABILITY or FITNESS FOR A
# PARTICULAR PURPOSE.



SHELL = /bin/sh

srcdir = .
top_srcdir = ..

prefix = /usr/local
exec_prefix = ${prefix}

bindir = ${exec_prefix}/bin
sbindir = ${exec_prefix}/sbin
libexecdir = ${exec_prefix}/libexec
datadir = ${prefix}/share
sysconfdir = ${prefix}/etc
sharedstatedir = ${prefix}/com
localstatedir = ${prefix}/var
libdir = ${exec_prefix}/lib
infodir = ${prefix}/info
mandir = ${prefix}/man
includedir = ${prefix}/include
oldincludedir = /usr/include
pkgdatadir = $(datadir)/pxtools
pkglibdir = $(libdir)/pxtools
pkgincludedir = $(includedir)/pxtools
top_builddir = ..

ACLOCAL = ${SHELL} /root/Download/qt/examples/dviz/src/pxtools-0.0.20/missing --run aclocal
AUTOCONF = ${SHELL} /root/Download/qt/examples/dviz/src/pxtools-0.0.20/missing --run autoconf
AUTOMAKE = ${SHELL} /root/Download/qt/examples/dviz/src/pxtools-0.0.20/missing --run automake
AUTOHEADER = ${SHELL} /root/Download/qt/examples/dviz/src/pxtools-0.0.20/missing --run autoheader

INSTALL = /usr/bin/install -c
INSTALL_PROGRAM = ${INSTALL}
INSTALL_DATA = ${INSTALL} -m 644
INSTALL_SCRIPT = ${INSTALL}
INSTALL_HEADER = $(INSTALL_DATA)
transform = s,x,x,
NORMAL_INSTALL = :
PRE_INSTALL = :
POST_INSTALL = :
NORMAL_UNINSTALL = :
PRE_UNINSTALL = :
POST_UNINSTALL = :
host_alias = i686-pc-linux-gnu
host_triplet = i686-pc-linux-gnu
AMTAR = ${SHELL} /root/Download/qt/examples/dviz/src/pxtools-0.0.20/missing --run tar
AWK = gawk
BUILD_INCLUDED_LIBINTL = no
CATALOGS =  de.gmo
CATOBJEXT = .gmo
CC = gcc
DATADIRNAME = share
DEPDIR = .deps
EXEEXT = 
GENCAT = gencat
GLIBC21 = yes
GMOFILES =  de.gmo
GMSGFMT = /usr/bin/msgfmt
INSTALL_STRIP_PROGRAM = ${SHELL} $(install_sh) -c -s
INSTOBJEXT = .mo
INTLBISON = bison
INTLINC = 
INTLLIBS = 
INTLOBJS = 
INTL_LIBTOOL_SUFFIX_PREFIX = 
LIBICONV = 
MAINT = #
MKINSTALLDIRS = ./mkinstalldirs
MSGFMT = /usr/bin/msgfmt
OBJEXT = o
PACKAGE = pxtools
POFILES =  de.po
POSUB = po
RANLIB = ranlib
USE_INCLUDED_LIBINTL = no
USE_NLS = yes
VERSION = 0.0.20
am__include = include
am__quote = 
install_sh = /root/Download/qt/examples/dviz/src/pxtools-0.0.20/install-sh
localedir = ${datadir}/locale

bin_PROGRAMS = pxinfo pxsqldump pxcsvdump pxxmldump

pxinfo_SOURCES = pxparse.c pxconvert.c pxinfo.c 
pxsqldump_SOURCES = pxparse.c pxconvert.c pxsqldump.c 
pxcsvdump_SOURCES = pxparse.c pxconvert.c pxcsvdump.c 
pxxmldump_SOURCES = pxparse.c pxconvert.c pxxmldump.c 

noinst_HEADERS = pxtypes.h pxconvert.h pxparse.h

CFLAGS = -g -Wall -O2 #-DDEBUG -DDEBUG_HEAD_COPY
DEFS = -DHAVE_CONFIG_H -DLOCALEDIR=\"$(localedir)\" 

pxinfo_LDADD = $(INTLLIBS)
pxsqldump_LDADD = $(INTLLIBS)
pxcsvdump_LDADD = $(INTLLIBS)
pxxmldump_LDADD = $(INTLLIBS)
subdir = src
mkinstalldirs = $(SHELL) $(top_srcdir)/mkinstalldirs
CONFIG_HEADER = $(top_builddir)/config.h
CONFIG_CLEAN_FILES =
bin_PROGRAMS = pxinfo$(EXEEXT) pxsqldump$(EXEEXT) pxcsvdump$(EXEEXT) \
	pxxmldump$(EXEEXT)
PROGRAMS = $(bin_PROGRAMS)

am_pxcsvdump_OBJECTS = pxparse.$(OBJEXT) pxconvert.$(OBJEXT) \
	pxcsvdump.$(OBJEXT)
pxcsvdump_OBJECTS = $(am_pxcsvdump_OBJECTS)
pxcsvdump_DEPENDENCIES =
pxcsvdump_LDFLAGS =
am_pxinfo_OBJECTS = pxparse.$(OBJEXT) pxconvert.$(OBJEXT) \
	pxinfo.$(OBJEXT)
pxinfo_OBJECTS = $(am_pxinfo_OBJECTS)
pxinfo_DEPENDENCIES =
pxinfo_LDFLAGS =
am_pxsqldump_OBJECTS = pxparse.$(OBJEXT) pxconvert.$(OBJEXT) \
	pxsqldump.$(OBJEXT)
pxsqldump_OBJECTS = $(am_pxsqldump_OBJECTS)
pxsqldump_DEPENDENCIES =
pxsqldump_LDFLAGS =
am_pxxmldump_OBJECTS = pxparse.$(OBJEXT) pxconvert.$(OBJEXT) \
	pxxmldump.$(OBJEXT)
pxxmldump_OBJECTS = $(am_pxxmldump_OBJECTS)
pxxmldump_DEPENDENCIES =
pxxmldump_LDFLAGS =
DEFAULT_INCLUDES =  -I. -I$(srcdir) -I$(top_builddir)
CPPFLAGS = 
LDFLAGS = 
LIBS = 
depcomp = $(SHELL) $(top_srcdir)/depcomp
DEP_FILES = $(DEPDIR)/pxconvert.Po $(DEPDIR)/pxcsvdump.Po \
	$(DEPDIR)/pxinfo.Po $(DEPDIR)/pxparse.Po \
	$(DEPDIR)/pxsqldump.Po $(DEPDIR)/pxxmldump.Po
COMPILE = $(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) \
	$(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS)
CCLD = $(CC)
LINK = $(CCLD) $(AM_CFLAGS) $(CFLAGS) $(AM_LDFLAGS) $(LDFLAGS) -o $@
DIST_SOURCES = $(pxcsvdump_SOURCES) $(pxinfo_SOURCES) \
	$(pxsqldump_SOURCES) $(pxxmldump_SOURCES)
HEADERS = $(noinst_HEADERS)

DIST_COMMON = $(noinst_HEADERS) Makefile.am Makefile.in
SOURCES = $(pxcsvdump_SOURCES) $(pxinfo_SOURCES) $(pxsqldump_SOURCES) $(pxxmldump_SOURCES)

all: all-am

.SUFFIXES:
.SUFFIXES: .c .o .obj
$(srcdir)/Makefile.in: # Makefile.am  $(top_srcdir)/configure.in $(ACLOCAL_M4)
	cd $(top_srcdir) && \
	  $(AUTOMAKE) --gnu  src/Makefile
Makefile: # $(srcdir)/Makefile.in  $(top_builddir)/config.status
	cd $(top_builddir) && \
	  CONFIG_HEADERS= CONFIG_LINKS= \
	  CONFIG_FILES=$(subdir)/$@ $(SHELL) ./config.status
install-binPROGRAMS: $(bin_PROGRAMS)
	@$(NORMAL_INSTALL)
	$(mkinstalldirs) $(DESTDIR)$(bindir)
	@list='$(bin_PROGRAMS)'; for p in $$list; do \
	  p1=`echo $$p|sed 's/$(EXEEXT)$$//'`; \
	  if test -f $$p \
	  ; then \
	    f=`echo $$p1|sed '$(transform);s/$$/$(EXEEXT)/'`; \
	   echo " $(INSTALL_PROGRAM_ENV) $(INSTALL_PROGRAM) $$p $(DESTDIR)$(bindir)/$$f"; \
	   $(INSTALL_PROGRAM_ENV) $(INSTALL_PROGRAM) $$p $(DESTDIR)$(bindir)/$$f; \
	  else :; fi; \
	done

uninstall-binPROGRAMS:
	@$(NORMAL_UNINSTALL)
	@list='$(bin_PROGRAMS)'; for p in $$list; do \
	  f=`echo $$p|sed 's/$(EXEEXT)$$//;$(transform);s/$$/$(EXEEXT)/'`; \
	  echo " rm -f $(DESTDIR)$(bindir)/$$f"; \
	  rm -f $(DESTDIR)$(bindir)/$$f; \
	done

clean-binPROGRAMS:
	-test -z "$(bin_PROGRAMS)" || rm -f $(bin_PROGRAMS)
pxcsvdump$(EXEEXT): $(pxcsvdump_OBJECTS) $(pxcsvdump_DEPENDENCIES) 
	@rm -f pxcsvdump$(EXEEXT)
	$(LINK) $(pxcsvdump_LDFLAGS) $(pxcsvdump_OBJECTS) $(pxcsvdump_LDADD) $(LIBS)
pxinfo$(EXEEXT): $(pxinfo_OBJECTS) $(pxinfo_DEPENDENCIES) 
	@rm -f pxinfo$(EXEEXT)
	$(LINK) $(pxinfo_LDFLAGS) $(pxinfo_OBJECTS) $(pxinfo_LDADD) $(LIBS)
pxsqldump$(EXEEXT): $(pxsqldump_OBJECTS) $(pxsqldump_DEPENDENCIES) 
	@rm -f pxsqldump$(EXEEXT)
	$(LINK) $(pxsqldump_LDFLAGS) $(pxsqldump_OBJECTS) $(pxsqldump_LDADD) $(LIBS)
pxxmldump$(EXEEXT): $(pxxmldump_OBJECTS) $(pxxmldump_DEPENDENCIES) 
	@rm -f pxxmldump$(EXEEXT)
	$(LINK) $(pxxmldump_LDFLAGS) $(pxxmldump_OBJECTS) $(pxxmldump_LDADD) $(LIBS)

mostlyclean-compile:
	-rm -f *.$(OBJEXT) core *.core

distclean-compile:
	-rm -f *.tab.c

include $(DEPDIR)/pxconvert.Po
include $(DEPDIR)/pxcsvdump.Po
include $(DEPDIR)/pxinfo.Po
include $(DEPDIR)/pxparse.Po
include $(DEPDIR)/pxsqldump.Po
include $(DEPDIR)/pxxmldump.Po

distclean-depend:
	-rm -rf $(DEPDIR)

.c.o:
	source='$<' object='$@' libtool=no \
	depfile='$(DEPDIR)/$*.Po' tmpdepfile='$(DEPDIR)/$*.TPo' \
	$(CCDEPMODE) $(depcomp) \
	$(COMPILE) -c `test -f $< || echo '$(srcdir)/'`$<

.c.obj:
	source='$<' object='$@' libtool=no \
	depfile='$(DEPDIR)/$*.Po' tmpdepfile='$(DEPDIR)/$*.TPo' \
	$(CCDEPMODE) $(depcomp) \
	$(COMPILE) -c `cygpath -w $<`
CCDEPMODE = depmode=gcc3
uninstall-info-am:

tags: TAGS

ID: $(HEADERS) $(SOURCES) $(LISP) $(TAGS_FILES)
	list='$(SOURCES) $(HEADERS) $(TAGS_FILES)'; \
	unique=`for i in $$list; do \
	    if test -f "$$i"; then echo $$i; else echo $(srcdir)/$$i; fi; \
	  done | \
	  $(AWK) '    { files[$$0] = 1; } \
	       END { for (i in files) print i; }'`; \
	mkid -fID $$unique $(LISP)

TAGS:  $(HEADERS) $(SOURCES)  $(TAGS_DEPENDENCIES) \
		$(TAGS_FILES) $(LISP)
	tags=; \
	here=`pwd`; \
	list='$(SOURCES) $(HEADERS) $(TAGS_FILES)'; \
	unique=`for i in $$list; do \
	    if test -f "$$i"; then echo $$i; else echo $(srcdir)/$$i; fi; \
	  done | \
	  $(AWK) '    { files[$$0] = 1; } \
	       END { for (i in files) print i; }'`; \
	test -z "$(ETAGS_ARGS)$$unique$(LISP)$$tags" \
	  || etags $(ETAGS_ARGS) $$tags  $$unique $(LISP)

GTAGS:
	here=`CDPATH=: && cd $(top_builddir) && pwd` \
	  && cd $(top_srcdir) \
	  && gtags -i $(GTAGS_ARGS) $$here

distclean-tags:
	-rm -f TAGS ID GTAGS GRTAGS GSYMS GPATH

DISTFILES = $(DIST_COMMON) $(DIST_SOURCES) $(TEXINFOS) $(EXTRA_DIST)

top_distdir = ..
distdir = $(top_distdir)/$(PACKAGE)-$(VERSION)

distdir: $(DISTFILES)
	@for file in $(DISTFILES); do \
	  if test -f $$file; then d=.; else d=$(srcdir); fi; \
	  dir=`echo "$$file" | sed -e 's,/[^/]*$$,,'`; \
	  if test "$$dir" != "$$file" && test "$$dir" != "."; then \
	    $(mkinstalldirs) "$(distdir)/$$dir"; \
	  fi; \
	  if test -d $$d/$$file; then \
	    cp -pR $$d/$$file $(distdir) \
	    || exit 1; \
	  else \
	    test -f $(distdir)/$$file \
	    || cp -p $$d/$$file $(distdir)/$$file \
	    || exit 1; \
	  fi; \
	done
check-am: all-am
check: check-am
all-am: Makefile $(PROGRAMS) $(HEADERS)

installdirs:
	$(mkinstalldirs) $(DESTDIR)$(bindir)

install: install-am
install-exec: install-exec-am
install-data: install-data-am
uninstall: uninstall-am

install-am: all-am
	@$(MAKE) $(AM_MAKEFLAGS) install-exec-am install-data-am

installcheck: installcheck-am
install-strip:
	$(MAKE) $(AM_MAKEFLAGS) INSTALL_PROGRAM="$(INSTALL_STRIP_PROGRAM)" \
	  `test -z '$(STRIP)' || \
	    echo "INSTALL_PROGRAM_ENV=STRIPPROG='$(STRIP)'"` install
mostlyclean-generic:

clean-generic:

distclean-generic:
	-rm -f Makefile $(CONFIG_CLEAN_FILES) stamp-h stamp-h[0-9]*

maintainer-clean-generic:
	@echo "This command is intended for maintainers to use"
	@echo "it deletes files that may require special tools to rebuild."
clean: clean-am

clean-am: clean-binPROGRAMS clean-generic mostlyclean-am

distclean: distclean-am

distclean-am: clean-am distclean-compile distclean-depend \
	distclean-generic distclean-tags

dvi: dvi-am

dvi-am:

info: info-am

info-am:

install-data-am:

install-exec-am: install-binPROGRAMS

install-info: install-info-am

install-man:

installcheck-am:

maintainer-clean: maintainer-clean-am

maintainer-clean-am: distclean-am maintainer-clean-generic

mostlyclean: mostlyclean-am

mostlyclean-am: mostlyclean-compile mostlyclean-generic

uninstall-am: uninstall-binPROGRAMS uninstall-info-am

.PHONY: GTAGS all all-am check check-am clean clean-binPROGRAMS \
	clean-generic distclean distclean-compile distclean-depend \
	distclean-generic distclean-tags distdir dvi dvi-am info \
	info-am install install-am install-binPROGRAMS install-data \
	install-data-am install-exec install-exec-am install-info \
	install-info-am install-man install-strip installcheck \
	installcheck-am installdirs maintainer-clean \
	maintainer-clean-generic mostlyclean mostlyclean-compile \
	mostlyclean-generic tags uninstall uninstall-am \
	uninstall-binPROGRAMS uninstall-info-am

# Tell versions [3.59,3.63) of GNU make to not export all variables.
# Otherwise a system limit (for SysV at least) may be exceeded.
.NOEXPORT:
