######################################################################
# Automatically generated by qmake (2.01a) Wed Oct 28 17:11:42 2009
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += pxconvert.h pxparse.h pxtypes.h
SOURCES += pxconvert.c pxparse.c  pxxml-text.c
#pxsqldump.c pxcsvdump.c pxinfo.c 
