######################################################################
# Automatically generated by qmake (2.01a) Sun Nov 27 14:19:35 2011
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

QT += network

# Input
HEADERS += MidiReader.h \
	MidiServer.h \
	MidiServerThread.h
SOURCES += MidiReader.cpp \
	MidiServer.cpp \
	MidiServerThread.cpp \
	main.cpp 
